services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/bots.d:/etc/nginx/bots.d
      - ./data/nginx/sites-available:/etc/nginx/sites-available
      - ./data/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /usr/local/share/data:/usr/share/nginx/html/thumbnails
    ports:
      - "80:80"
      - "443:443"
    command: |
      /bin/sh -c '
        apk update &&
        apk add --no-cache curl bind-tools busybox-extras mailx ssmtp openssl &&
        mkdir -p /usr/local/sbin &&
        wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/refs/heads/master/install-ngxblocker -O /usr/local/sbin/install-ngxblocker &&
        wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/refs/heads/master/update-ngxblocker -O /usr/local/sbin/update-ngxblocker &&
        chmod +x /usr/local/sbin/install-ngxblocker &&
        chmod +x /usr/local/sbin/update-ngxblocker &&
        echo "00 */8 * * * /usr/local/sbin/update-ngxblocker -e sjsage522.dev@gmail.com" > /etc/crontabs/root &&
        crond &&
        while :; do
          sleep 6h &
          wait $${!};
          nginx -s reload;
        done &
        nginx -g "daemon off;"
      '

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

